[tool.pylint.messages_control]

disable = [
    "invalid-name",
    "f-string-without-interpolation",
    "too-few-public-methods",
    "import-error",
    "protected-access",
    "too-many-arguments",
    "too-many-locals",
    "no-else-return",
    "no-value-for-parameter",
    "duplicate-code"
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = false

[tool.pytest.ini_options]
pythonpath = [
  ".", "refactor_rossmann",
]