defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

data_preparation:
  robust_scaler:
      - CompetitionDistance
      - competition_time_month
  min_max_scaler:
      - promo_time_week
      - year
  onehot:
      - StateHoliday
      - StoreType
  ordinal:
      - Assortment
